/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Mode = IDL.Variant({
  'math' : IDL.Null,
  'chemistry' : IDL.Null,
  'physics' : IDL.Null,
});
export const Step = IDL.Record({
  'result' : IDL.Opt(IDL.Float64),
  'calculation' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
});
export const Answer = IDL.Record({
  'value' : IDL.Float64,
  'units' : IDL.Opt(IDL.Text),
});
export const Result = IDL.Record({
  'steps' : IDL.Vec(Step),
  'finalAnswer' : Answer,
});
export const PhysicsTopic = IDL.Variant({
  'kinematics' : IDL.Null,
  'ohmsLaw' : IDL.Null,
  'newtonsSecondLaw' : IDL.Null,
  'power' : IDL.Null,
  'workEnergy' : IDL.Null,
});
export const ChemistryTopic = IDL.Variant({
  'ph' : IDL.Null,
  'molesMassConversion' : IDL.Null,
  'dilution' : IDL.Null,
  'molarity' : IDL.Null,
  'molarMass' : IDL.Null,
  'idealGasLaw' : IDL.Null,
});
export const Input = IDL.Variant({
  'physicsProblem' : IDL.Record({
    'topic' : PhysicsTopic,
    'values' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  }),
  'mathExpression' : IDL.Text,
  'chemistryProblem' : IDL.Record({
    'topic' : ChemistryTopic,
    'values' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  }),
});
export const Item = IDL.Record({
  'id' : IDL.Nat,
  'mode' : Mode,
  'answer' : Result,
  'timestamp' : IDL.Int,
  'input' : Input,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearHistory' : IDL.Func([], [], []),
  'deleteHistoryItem' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversionFactor' : IDL.Func([IDL.Text, IDL.Text], [IDL.Float64], []),
  'getHistory' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'getHistoryItem' : IDL.Func([IDL.Nat], [IDL.Opt(Item)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listChemistryTopics' : IDL.Func([], [IDL.Vec(ChemistryTopic)], ['query']),
  'listPhysicsTopics' : IDL.Func([], [IDL.Vec(PhysicsTopic)], ['query']),
  'reRunHistoryItem' : IDL.Func([IDL.Nat], [Result], []),
  'runCalculation' : IDL.Func([Input], [Result], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'suggestUnits' : IDL.Func([IDL.Float64, IDL.Text], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Mode = IDL.Variant({
    'math' : IDL.Null,
    'chemistry' : IDL.Null,
    'physics' : IDL.Null,
  });
  const Step = IDL.Record({
    'result' : IDL.Opt(IDL.Float64),
    'calculation' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
  });
  const Answer = IDL.Record({
    'value' : IDL.Float64,
    'units' : IDL.Opt(IDL.Text),
  });
  const Result = IDL.Record({
    'steps' : IDL.Vec(Step),
    'finalAnswer' : Answer,
  });
  const PhysicsTopic = IDL.Variant({
    'kinematics' : IDL.Null,
    'ohmsLaw' : IDL.Null,
    'newtonsSecondLaw' : IDL.Null,
    'power' : IDL.Null,
    'workEnergy' : IDL.Null,
  });
  const ChemistryTopic = IDL.Variant({
    'ph' : IDL.Null,
    'molesMassConversion' : IDL.Null,
    'dilution' : IDL.Null,
    'molarity' : IDL.Null,
    'molarMass' : IDL.Null,
    'idealGasLaw' : IDL.Null,
  });
  const Input = IDL.Variant({
    'physicsProblem' : IDL.Record({
      'topic' : PhysicsTopic,
      'values' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
    }),
    'mathExpression' : IDL.Text,
    'chemistryProblem' : IDL.Record({
      'topic' : ChemistryTopic,
      'values' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
    }),
  });
  const Item = IDL.Record({
    'id' : IDL.Nat,
    'mode' : Mode,
    'answer' : Result,
    'timestamp' : IDL.Int,
    'input' : Input,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearHistory' : IDL.Func([], [], []),
    'deleteHistoryItem' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversionFactor' : IDL.Func([IDL.Text, IDL.Text], [IDL.Float64], []),
    'getHistory' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'getHistoryItem' : IDL.Func([IDL.Nat], [IDL.Opt(Item)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listChemistryTopics' : IDL.Func([], [IDL.Vec(ChemistryTopic)], ['query']),
    'listPhysicsTopics' : IDL.Func([], [IDL.Vec(PhysicsTopic)], ['query']),
    'reRunHistoryItem' : IDL.Func([IDL.Nat], [Result], []),
    'runCalculation' : IDL.Func([Input], [Result], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'suggestUnits' : IDL.Func([IDL.Float64, IDL.Text], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };