/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Answer { 'value' : number, 'units' : [] | [string] }
export type ChemistryTopic = { 'ph' : null } |
  { 'molesMassConversion' : null } |
  { 'dilution' : null } |
  { 'molarity' : null } |
  { 'molarMass' : null } |
  { 'idealGasLaw' : null };
export type Input = {
    'physicsProblem' : {
      'topic' : PhysicsTopic,
      'values' : Array<[string, number]>,
    }
  } |
  { 'mathExpression' : string } |
  {
    'chemistryProblem' : {
      'topic' : ChemistryTopic,
      'values' : Array<[string, number]>,
    }
  };
export interface Item {
  'id' : bigint,
  'mode' : Mode,
  'answer' : Result,
  'timestamp' : bigint,
  'input' : Input,
}
export type Mode = { 'math' : null } |
  { 'chemistry' : null } |
  { 'physics' : null };
export type PhysicsTopic = { 'kinematics' : null } |
  { 'ohmsLaw' : null } |
  { 'newtonsSecondLaw' : null } |
  { 'power' : null } |
  { 'workEnergy' : null };
export interface Result { 'steps' : Array<Step>, 'finalAnswer' : Answer }
export interface Step {
  'result' : [] | [number],
  'calculation' : [] | [string],
  'description' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearHistory' : ActorMethod<[], undefined>,
  'deleteHistoryItem' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversionFactor' : ActorMethod<[string, string], number>,
  'getHistory' : ActorMethod<[], Array<Item>>,
  'getHistoryItem' : ActorMethod<[bigint], [] | [Item]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listChemistryTopics' : ActorMethod<[], Array<ChemistryTopic>>,
  'listPhysicsTopics' : ActorMethod<[], Array<PhysicsTopic>>,
  'reRunHistoryItem' : ActorMethod<[bigint], Result>,
  'runCalculation' : ActorMethod<[Input], Result>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'suggestUnits' : ActorMethod<[number, string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];