/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Input = {
    __kind__: "physicsProblem";
    physicsProblem: {
        topic: PhysicsTopic;
        values: Array<[string, number]>;
    };
} | {
    __kind__: "mathExpression";
    mathExpression: string;
} | {
    __kind__: "chemistryProblem";
    chemistryProblem: {
        topic: ChemistryTopic;
        values: Array<[string, number]>;
    };
};
export interface Item {
    id: bigint;
    mode: Mode;
    answer: Result;
    timestamp: bigint;
    input: Input;
}
export interface Result {
    steps: Array<Step>;
    finalAnswer: Answer;
}
export interface Answer {
    value: number;
    units?: string;
}
export interface Step {
    result?: number;
    calculation?: string;
    description: string;
}
export interface UserProfile {
    name: string;
}
export enum ChemistryTopic {
    ph = "ph",
    molesMassConversion = "molesMassConversion",
    dilution = "dilution",
    molarity = "molarity",
    molarMass = "molarMass",
    idealGasLaw = "idealGasLaw"
}
export enum Mode {
    math = "math",
    chemistry = "chemistry",
    physics = "physics"
}
export enum PhysicsTopic {
    kinematics = "kinematics",
    ohmsLaw = "ohmsLaw",
    newtonsSecondLaw = "newtonsSecondLaw",
    power = "power",
    workEnergy = "workEnergy"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearHistory(): Promise<void>;
    deleteHistoryItem(id: bigint): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getConversionFactor(fromUnits: string, toUnits: string): Promise<number>;
    getHistory(): Promise<Array<Item>>;
    getHistoryItem(id: bigint): Promise<Item | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listChemistryTopics(): Promise<Array<ChemistryTopic>>;
    listPhysicsTopics(): Promise<Array<PhysicsTopic>>;
    reRunHistoryItem(id: bigint): Promise<Result>;
    runCalculation(input: Input): Promise<Result>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    suggestUnits(value: number, units: string): Promise<string>;
}
import type { Answer as _Answer, ChemistryTopic as _ChemistryTopic, Input as _Input, Item as _Item, Mode as _Mode, PhysicsTopic as _PhysicsTopic, Result as _Result, Step as _Step, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearHistory(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearHistory();
            return result;
        }
    }
    async deleteHistoryItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHistoryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHistoryItem(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversionFactor(arg0: string, arg1: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversionFactor(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversionFactor(arg0, arg1);
            return result;
        }
    }
    async getHistory(): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHistory();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHistory();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHistoryItem(arg0: bigint): Promise<Item | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHistoryItem(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHistoryItem(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listChemistryTopics(): Promise<Array<ChemistryTopic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listChemistryTopics();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listChemistryTopics();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPhysicsTopics(): Promise<Array<PhysicsTopic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPhysicsTopics();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPhysicsTopics();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async reRunHistoryItem(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.reRunHistoryItem(arg0);
                return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reRunHistoryItem(arg0);
            return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async runCalculation(arg0: Input): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.runCalculation(to_candid_Input_n31(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.runCalculation(to_candid_Input_n31(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async suggestUnits(arg0: number, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.suggestUnits(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.suggestUnits(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Answer_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Answer): Answer {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_ChemistryTopic_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChemistryTopic): ChemistryTopic {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Input_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Input): Input {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Item_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Item): Item {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Mode_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Mode): Mode {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_PhysicsTopic_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PhysicsTopic): PhysicsTopic {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Step_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Step): Step {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Item]): Item | null {
    return value.length === 0 ? null : from_candid_Item_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    steps: Array<_Step>;
    finalAnswer: _Answer;
}): {
    steps: Array<Step>;
    finalAnswer: Answer;
} {
    return {
        steps: from_candid_vec_n13(_uploadFile, _downloadFile, value.steps),
        finalAnswer: from_candid_Answer_n18(_uploadFile, _downloadFile, value.finalAnswer)
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    result: [] | [number];
    calculation: [] | [string];
    description: string;
}): {
    result?: number;
    calculation?: string;
    description: string;
} {
    return {
        result: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.result)),
        calculation: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.calculation)),
        description: value.description
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: number;
    units: [] | [string];
}): {
    value: number;
    units?: string;
} {
    return {
        value: value.value,
        units: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.units))
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    topic: _PhysicsTopic;
    values: Array<[string, number]>;
}): {
    topic: PhysicsTopic;
    values: Array<[string, number]>;
} {
    return {
        topic: from_candid_PhysicsTopic_n23(_uploadFile, _downloadFile, value.topic),
        values: value.values
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    topic: _ChemistryTopic;
    values: Array<[string, number]>;
}): {
    topic: ChemistryTopic;
    values: Array<[string, number]>;
} {
    return {
        topic: from_candid_ChemistryTopic_n26(_uploadFile, _downloadFile, value.topic),
        values: value.values
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    mode: _Mode;
    answer: _Result;
    timestamp: bigint;
    input: _Input;
}): {
    id: bigint;
    mode: Mode;
    answer: Result;
    timestamp: bigint;
    input: Input;
} {
    return {
        id: value.id,
        mode: from_candid_Mode_n9(_uploadFile, _downloadFile, value.mode),
        answer: from_candid_Result_n11(_uploadFile, _downloadFile, value.answer),
        timestamp: value.timestamp,
        input: from_candid_Input_n20(_uploadFile, _downloadFile, value.input)
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    math: null;
} | {
    chemistry: null;
} | {
    physics: null;
}): Mode {
    return "math" in value ? Mode.math : "chemistry" in value ? Mode.chemistry : "physics" in value ? Mode.physics : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    physicsProblem: {
        topic: _PhysicsTopic;
        values: Array<[string, number]>;
    };
} | {
    mathExpression: string;
} | {
    chemistryProblem: {
        topic: _ChemistryTopic;
        values: Array<[string, number]>;
    };
}): {
    __kind__: "physicsProblem";
    physicsProblem: {
        topic: PhysicsTopic;
        values: Array<[string, number]>;
    };
} | {
    __kind__: "mathExpression";
    mathExpression: string;
} | {
    __kind__: "chemistryProblem";
    chemistryProblem: {
        topic: ChemistryTopic;
        values: Array<[string, number]>;
    };
} {
    return "physicsProblem" in value ? {
        __kind__: "physicsProblem",
        physicsProblem: from_candid_record_n22(_uploadFile, _downloadFile, value.physicsProblem)
    } : "mathExpression" in value ? {
        __kind__: "mathExpression",
        mathExpression: value.mathExpression
    } : "chemistryProblem" in value ? {
        __kind__: "chemistryProblem",
        chemistryProblem: from_candid_record_n25(_uploadFile, _downloadFile, value.chemistryProblem)
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    kinematics: null;
} | {
    ohmsLaw: null;
} | {
    newtonsSecondLaw: null;
} | {
    power: null;
} | {
    workEnergy: null;
}): PhysicsTopic {
    return "kinematics" in value ? PhysicsTopic.kinematics : "ohmsLaw" in value ? PhysicsTopic.ohmsLaw : "newtonsSecondLaw" in value ? PhysicsTopic.newtonsSecondLaw : "power" in value ? PhysicsTopic.power : "workEnergy" in value ? PhysicsTopic.workEnergy : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ph: null;
} | {
    molesMassConversion: null;
} | {
    dilution: null;
} | {
    molarity: null;
} | {
    molarMass: null;
} | {
    idealGasLaw: null;
}): ChemistryTopic {
    return "ph" in value ? ChemistryTopic.ph : "molesMassConversion" in value ? ChemistryTopic.molesMassConversion : "dilution" in value ? ChemistryTopic.dilution : "molarity" in value ? ChemistryTopic.molarity : "molarMass" in value ? ChemistryTopic.molarMass : "idealGasLaw" in value ? ChemistryTopic.idealGasLaw : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Step>): Array<Step> {
    return value.map((x)=>from_candid_Step_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChemistryTopic>): Array<ChemistryTopic> {
    return value.map((x)=>from_candid_ChemistryTopic_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PhysicsTopic>): Array<PhysicsTopic> {
    return value.map((x)=>from_candid_PhysicsTopic_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Item>): Array<Item> {
    return value.map((x)=>from_candid_Item_n7(_uploadFile, _downloadFile, x));
}
function to_candid_ChemistryTopic_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChemistryTopic): _ChemistryTopic {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_Input_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Input): _Input {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_PhysicsTopic_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PhysicsTopic): _PhysicsTopic {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    topic: ChemistryTopic;
    values: Array<[string, number]>;
}): {
    topic: _ChemistryTopic;
    values: Array<[string, number]>;
} {
    return {
        topic: to_candid_ChemistryTopic_n34(_uploadFile, _downloadFile, value.topic),
        values: value.values
    };
}
function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    topic: PhysicsTopic;
    values: Array<[string, number]>;
}): {
    topic: _PhysicsTopic;
    values: Array<[string, number]>;
} {
    return {
        topic: to_candid_PhysicsTopic_n37(_uploadFile, _downloadFile, value.topic),
        values: value.values
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "physicsProblem";
    physicsProblem: {
        topic: PhysicsTopic;
        values: Array<[string, number]>;
    };
} | {
    __kind__: "mathExpression";
    mathExpression: string;
} | {
    __kind__: "chemistryProblem";
    chemistryProblem: {
        topic: ChemistryTopic;
        values: Array<[string, number]>;
    };
}): {
    physicsProblem: {
        topic: _PhysicsTopic;
        values: Array<[string, number]>;
    };
} | {
    mathExpression: string;
} | {
    chemistryProblem: {
        topic: _ChemistryTopic;
        values: Array<[string, number]>;
    };
} {
    return value.__kind__ === "physicsProblem" ? {
        physicsProblem: to_candid_record_n36(_uploadFile, _downloadFile, value.physicsProblem)
    } : value.__kind__ === "mathExpression" ? {
        mathExpression: value.mathExpression
    } : value.__kind__ === "chemistryProblem" ? {
        chemistryProblem: to_candid_record_n33(_uploadFile, _downloadFile, value.chemistryProblem)
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChemistryTopic): {
    ph: null;
} | {
    molesMassConversion: null;
} | {
    dilution: null;
} | {
    molarity: null;
} | {
    molarMass: null;
} | {
    idealGasLaw: null;
} {
    return value == ChemistryTopic.ph ? {
        ph: null
    } : value == ChemistryTopic.molesMassConversion ? {
        molesMassConversion: null
    } : value == ChemistryTopic.dilution ? {
        dilution: null
    } : value == ChemistryTopic.molarity ? {
        molarity: null
    } : value == ChemistryTopic.molarMass ? {
        molarMass: null
    } : value == ChemistryTopic.idealGasLaw ? {
        idealGasLaw: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PhysicsTopic): {
    kinematics: null;
} | {
    ohmsLaw: null;
} | {
    newtonsSecondLaw: null;
} | {
    power: null;
} | {
    workEnergy: null;
} {
    return value == PhysicsTopic.kinematics ? {
        kinematics: null
    } : value == PhysicsTopic.ohmsLaw ? {
        ohmsLaw: null
    } : value == PhysicsTopic.newtonsSecondLaw ? {
        newtonsSecondLaw: null
    } : value == PhysicsTopic.power ? {
        power: null
    } : value == PhysicsTopic.workEnergy ? {
        workEnergy: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
